## numpy practice session

In [1]:
# import this lib in j.notebook
import numpy as np

## creating an array using numpy

In [2]:
np.array(["pakora", "samosa", "raita"])

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
food = np.array(["pakora", "samosa", "raita"])
food


array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [4]:
price= np.array([5,5,5])
price
#1-D array

array([5, 5, 5])

In [5]:
type(price) #ndarray n mean n dimensional array 

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
len(price)

3

In [9]:
price[2]

5

In [10]:
price[0:] #[0:] its mean zero to end all values

array([5, 5, 5])

In [11]:
# food["Samosa"] then error
food[1]

'samosa'

In [12]:
price.mean()

5.0

In [13]:
# range method ZEROS
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [14]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
# empty
np.empty(5) 
# assignment why here is 1's why not 0's

array([1., 1., 1., 1., 1.])

In [16]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
#specify range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [18]:
#specific range with interval
np.arange(2,20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
# table of five , 5 ka pahara
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [20]:
# line space, yani specific interval p 5 number ajy
np.linspace(0, 100, num=10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [21]:
np.linspace(1, 10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [22]:
#specify your data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [23]:

np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## array functions

In [24]:
a=np.array([10,20,30,50,2,5.2,10.5,3.2,320])
a

array([ 10. ,  20. ,  30. ,  50. ,   2. ,   5.2,  10.5,   3.2, 320. ])

In [25]:
a.sort()
a

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ])

In [26]:
a.cumsum()
a

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ])

In [27]:
b=np.array([10.2,11.5,22,5,50.5])
b

array([10.2, 11.5, 22. ,  5. , 50.5])

In [28]:
np.concatenate((a,b))

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ,
        10.2,  11.5,  22. ,   5. ,  50.5])

In [29]:
c= np.concatenate((a,b))
c

array([  2. ,   3.2,   5.2,  10. ,  10.5,  20. ,  30. ,  50. , 320. ,
        10.2,  11.5,  22. ,   5. ,  50.5])

In [31]:
np.sort(c)


array([  2. ,   3.2,   5. ,   5.2,  10. ,  10.2,  10.5,  11.5,  20. ,
        22. ,  30. ,  50. ,  50.5, 320. ])

In [34]:
c.sort()
c

array([  2. ,   3.2,   5. ,   5.2,  10. ,  10.2,  10.5,  11.5,  20. ,
        22. ,  30. ,  50. ,  50.5, 320. ])

## 2-D array

In [45]:
a= np.array([[1,2,3], [5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [46]:
b= np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [47]:
np.concatenate((a,b))

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 4, 5, 6],
       [5, 6, 7, 7, 8, 9]])

In [50]:
b.ndim #  .ndim = n dimensionS?

2

In [52]:
a.size   # calculte number of size of elements

6

In [53]:
a.shape   # shape : i,j,k i mean matrix , rows, coloumns

(2, 3)

In [56]:
a= np.arange(9) #3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
# reshape
b=a.reshape(3,3) #3*3
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
# reshape
np.reshape(a, newshape=(1,9), order="c") #3*3



array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [59]:
# covert 1D into 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
a.shape

(9,)

In [61]:
# row wise 2D coversion
b= a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [62]:
b.shape

(1, 9)

In [64]:
# coloumn wise 2D conversion
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [65]:
c.shape

(9, 1)

In [66]:
# multiplication *, addition+, sum a.sum(), a.mean()  
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [67]:
a.sum()

45

In [68]:
a.mean()

5.0