## 1-D array

In [4]:
import numpy as np
a= np.array([5,5,5])
a

array([5, 5, 5])

In [5]:
type(a)

numpy.ndarray

In [6]:
len(a)

3

In [7]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [14]:
# how to creat an array

import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [15]:
type(a)

numpy.ndarray

In [16]:
len(a)

5

In [29]:
b= np.zeros(2)
b

array([0., 0.])

In [18]:
c=np.ones(3)
c

array([1., 1., 1.])

In [21]:
# creat an empty array with 2 elements
d= np.empty(3)
d

array([1., 1., 1.])

In [41]:
# with specific range of elements
b=np.arange(2,20)
b

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [42]:
# with range of elements
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [43]:
# continue...
c=np.arange(2, 22, 2)
c

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
#linerly spaced array
d=np.linspace(0,10,num=5) #gives us 5 nums
d

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 2-D Array

In [32]:
import numpy as np
a= np.array([[5,5,5],[5,5,5],[5,5,5]])
a

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [46]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
import numpy as np
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [49]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
type(a)

numpy.ndarray

In [34]:
len(a)

3

In [35]:
a[0]

array([5, 5, 5])

In [36]:
a[0:]

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [27]:
import numpy as np
a= np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 3-D Array

In [50]:
#making and reshaping a 3D array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])